# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# Action 名称
name: .NET

# 定义触发条件
on:
  # 触发动作 push
  push:
    # 触发分支 main
    branches: [ "main" ]
  # 触发动作 pr
  pull_request:
    # 触发分支 main
    branches: [ "main" ]

# 定义 Job
jobs:
  # Job 名：build
  build:

    # 运行 Job 的 OS 环境
    runs-on: ubuntu-latest

    # 执行 Job 对应的步骤
    steps:
      # 迁出代码
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      # 安装 dotnet 7.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

      # 还原包
    - name: Restore dependencies
      run: dotnet restore

      # 执行 Build
    - name: Build
      run: dotnet build

      # 执行 Test
    - name: Test
      run: dotnet test  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        paths: ./**/coverage.opencover.xml
